# Generated by Django 4.2.6 on 2023-10-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='image', upload_to='images/'),
        ),
    ]
